# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Make sure the Specs repo is listed
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'arcalisNews' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # 👇 Add these two lines so CocoaPods uses the local podspecs in node_modules
  pod 'NitroModules',    :path => '../node_modules/react-native-nitro-modules'
 

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # 👇 (Optional but helps with some Nitro builds)
    installer.pods_project.targets.each do |t|
      if t.name == 'NitroModules'
        t.build_configurations.each { |c| c.build_settings['SWIFT_VERSION'] = '5.10' }
      end
    end
  end
end
